drgn: Use devlinks XArray to reach mlxsw data
Since kernel commit 698a1eb1f75e ("thermal: core: Store zone ops in
struct thermal_zone_device") the tool in unable to reach the mlxsw data
[1].

Fix by converting to use the global devlinks XArray instead. This should
work with both current and older kernels.

[1]
 # ./res_dump
 [...]
 TypeError: invalid operands to comparison ('struct thermal_zone_device_ops' and 'struct thermal_zone_device_ops *')

Signed-off-by: Ido Schimmel <idosch@nvidia.com>
Reviewed-by: Petr Machata <petrm@nvidia.com>